export const fakeJobs = [
	{
		id: 1,
		title: 'Desenvolvedor Front-end',
		status: 'Andamento',
		company: 'Tech Solutions Inc.',
		contract: 'CLT',
		modality: 'Presencial',
		salary: 75000,
	},
	{
		id: 2,
		title: 'Analista de Dados',
		status: 'Andamento',
		company: 'Data Analytics Co.',
		contract: 'PJ',
		modality: 'Remoto',
		salary: 60000,
	},
	{
		id: 3,
		title: 'Engenheiro de Software',
		status: 'Andamento',
		company: 'InnovateTech Ltd.',
		contract: 'CLT',
		modality: 'Hibrido',
		salary: 90000,
	},
	{
		id: 4,
		title: 'Especialista em Segurança da Informação',
		status: 'Andamento',
		company: 'SecureSys Corp.',
		contract: 'CLT',
		modality: 'Presencial',
		salary: 85000,
	},
	{
		id: 5,
		title: 'Designer UI/UX',
		status: 'Andamento',
		company: 'Creative Designs Studio',
		contract: 'PJ',
		modality: 'Presencial',
		salary: 70000,
	},
]
